title: "Julian Shyu"
description: "Portfolio and Resume"
# theme: jekyll-theme-minimal
url: "https://julianzen.github.io/julians.github.io/"
baseurl: "/julians.github.io"
author: "Julian Shyu"

include:
  - assets

# Navigation links
nav:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Projects
    link: /projects
  - name: Resume
    link: /resume
  - name: Contact
    link: /contact

# Build settings
markdown: kramdown
